# Secure Terraform module scaffold generated by SecEng-CoreTemplates.
# Add real resources here; this scaffold intentionally provisions nothing on its own.

locals {
  mission_config  = yamldecode(file("${path.module}/mission.yaml"))
  policy_config   = yamldecode(file("${path.module}/policy.yaml"))
  workflow_config = yamldecode(file("${path.module}/workflow.yaml"))
}
